// frontend/src/components/print/print-react/components/story/StoryDay.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text, View } from '@react-pdf/renderer'
import styles from '../styles.js'
import sortBy from 'lodash/sortBy.js'
import CategoryLabel from '../CategoryLabel.jsx'
import RichText from '../RichText.jsx'
import { dateLong } from '../../../../../common/helpers/dateHelperUTCFormatted.js'

function isEmptyHtml(html) {
  if (html === null) {
    return true
  }

  return html.trim() === '' || html.trim() === '<p></p>'
}

function StoryDay(props) {
  const sortedScheduleEntries = sortBy(
    props.period.scheduleEntries().items.filter((scheduleEntry) => {
      return scheduleEntry.day()._meta.self === props.day._meta.self
    }),
    (scheduleEntry) => scheduleEntry.start
  )
  const entries = sortedScheduleEntries.map((scheduleEntry) => ({
    scheduleEntry: scheduleEntry,
    storyChapters: props.period
      .contentNodes()
      .items.filter(
        (contentNode) =>
          contentNode.contentTypeName === 'Storycontext' &&
          contentNode.root()._meta.self ===
            scheduleEntry.activity().rootContentNode()._meta.self &&
          !isEmptyHtml(contentNode.data.text)
      ),
  }))
  const entriesWithStory = entries.filter(({ storyChapters }) => storyChapters.length)

  return (
    <React.Fragment>
      <Text
        id={`${props.id}-${props.period.id}-${props.day.id}`}
        style={{ ...styles.h2, marginTop: '12pt' }}
      >
        {props.$tc('entity.day.name')} {props.day.number} ({dateLong(props.day.start)})
      </Text>
      {entriesWithStory.map(({ scheduleEntry, storyChapters }) => {
        return (
          <React.Fragment key={scheduleEntry.id}>
            {storyChapters.map((chapter, idx) => {
              const chapterTitle =
                scheduleEntry.activity().title +
                (chapter.instanceName ? ' - ' + chapter.instanceName : '')
              return (
                <React.Fragment key={idx}>
                  <View
                    style={{
                      ...styles.h3,
                      display: 'flex',
                      flexDirection: 'row',
                      marginTop: '10pt',
                    }}
                    minPresenceAhead={30}
                  >
                    <Text id={`${props.id}-${props.period.id}-${scheduleEntry.id}`}>
                      {scheduleEntry.number}{' '}
                    </Text>
                    <CategoryLabel activity={scheduleEntry.activity()} />
                    <Text> {chapterTitle}</Text>
                  </View>
                  <RichText richText={chapter.data.text} />
                </React.Fragment>
              )
            })}
          </React.Fragment>
        )
      })}
    </React.Fragment>
  )
}

export default StoryDay

// print/components/story/StoryDay.vue
<template>
  <div class="tw-mb-4">
    <div class="tw-text-2xl tw-mb-2 tw-break-after-avoid">
      <h1>{{ $tc('entity.day.name') }} {{ day.number }} ({{ dateLong(day.start) }})</h1>
    </div>

    <template v-if="entriesWithStory.length">
      <template v-for="{ scheduleEntry, storyChapters } in entriesWithStory">
        <div v-for="chapter in storyChapters" :key="chapter._meta.uri" class="tw-mb-3">
          <h4 class="tw-text-lg tw-font-bold tw-break-after-avoid">
            <span class="d-inline-flex align-center">
              <span>{{ scheduleEntry.number }}</span>
              <category-label
                :category="scheduleEntry.activity().category()"
                class="tw-ml-1"
              />
            </span>

            <span>{{ scheduleEntry.activity().title }}</span>
            <template v-if="chapter.instanceName">
              - {{ chapter.instanceName }}
            </template>
          </h4>

          <rich-text :rich-text="chapter.data.text" />
        </div>
      </template>
    </template>
    <p v-else>
      {{ $tc('story.storyDay.noStory') }}
    </p>

    <hr />
  </div>
</template>

<script>
import CategoryLabel from '@/components/generic/CategoryLabel.vue'
import RichText from '@/components/generic/RichText.vue'
import { dateLong } from '@/../common/helpers/dateHelperUTCFormatted.js'

function isEmptyHtml(html) {
  if (html === null) {
    return true
  }

  return html.trim() === '' || html.trim() === '<p></p>'
}

export default {
  components: { CategoryLabel, RichText },
  props: {
    day: { type: Object, required: true },
    index: { type: Number, required: true },
    periodStoryChapters: { type: Array, required: true },
  },
  data() {
    return {}
  },
  computed: {
    // returns scheduleEntries of current day without the need for an additional API call
    scheduleEntries() {
      return this.day
        .period()
        .scheduleEntries()
        .items.filter((scheduleEntry) => {
          return scheduleEntry.day()._meta.self === this.day._meta.self
        })
    },

    entries() {
      return this.scheduleEntries.map((scheduleEntry) => ({
        scheduleEntry,
        storyChapters: this.periodStoryChapters.filter(
          (contentNode) =>
            contentNode.root()._meta.self ===
              scheduleEntry.activity().rootContentNode()._meta.self &&
            !isEmptyHtml(contentNode.data.text)
        ),
      }))
    },
    entriesWithStory() {
      return this.entries.filter(({ storyChapters }) => storyChapters.length)
    },
  },
  methods: {
    dateLong,
  },
}
</script>
