// frontend/src/components/print/print-react/components/story/Story.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Page } from '@react-pdf/renderer'
import styles from '../styles.js'
import StoryPeriod from './StoryPeriod.jsx'

function Story(props) {
  return (
    <Page key={props.id} style={styles.page} id={props.id}>
      {props.content.options.periods.map((periodUri) => (
        <StoryPeriod key={periodUri} periodUri={periodUri} {...props} />
      ))}
    </Page>
  )
}

export default Story

// pdf/src/campPrint/story/Story.vue
<template>
  <Page :id="id" class="page">
    <StoryPeriod v-for="period in periods" :id="id" :key="period.id" :period="period" />
  </Page>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import StoryPeriod from './StoryPeriod.vue'

export default {
  name: 'Story',
  components: { StoryPeriod },
  extends: PdfComponent,
  props: {
    content: { type: Object, required: true },
    config: { type: Object, required: true },
  },
  computed: {
    periods() {
      return this.content.options.periods.map((periodUri) => this.api.get(periodUri))
    },
  },
}
</script>
<pdf-style>
</pdf-style>
