// frontend/src/components/print/print-react/components/story/StoryPeriod.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text } from '@react-pdf/renderer'
import styles from '../styles.js'
import StoryDay from './StoryDay.jsx'

function StoryPeriod(props) {
  const period = props.store.get(props.periodUri)
  return (
    <React.Fragment>
      <Text
        id={`${props.id}-${period.id}`}
        bookmark={{
          title: props.$tc('print.story.title') + ': ' + period.description,
          fit: true,
        }}
        style={styles.h1}
      >
        {props.$tc('print.story.title')}: {period.description}
      </Text>
      {period.days().items.map((day) => (
        <StoryDay key={day.id} day={day} period={period} {...props} />
      ))}
    </React.Fragment>
  )
}

export default StoryPeriod

// pdf/src/campPrint/story/StoryPeriod.vue
<template>
  <Text
    :id="`${id}-${period.id}`"
    :bookmark="{ title: $tc('print.story.title') + ': ' + period.description, fit: true }"
    class="h1"
    >{{ $tc('print.story.title') }}: {{ period.description }}</Text
  >
  <StoryDay v-for="day in days" :id="id" :key="day.id" :period="period" :day="day" />
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import StoryDay from './StoryDay.vue'
import sortBy from 'lodash/sortBy.js'

export default {
  name: 'StoryPeriod',
  components: { StoryDay },
  extends: PdfComponent,
  props: {
    period: { type: Object, required: true },
  },
  computed: {
    days() {
      return sortBy(this.period.days().items, (day) => this.$date.utc(day.start).unix())
    },
  },
}
</script>
<pdf-style>
</pdf-style>
