// print/components/scheduleEntry/contentNode/LAThematicArea.vue
<template>
  <content-node-content :content-node="contentNode">
    <div v-for="option in selectedOptions" :key="option.translateKey" class="entry">
      <check-mark :size="12" />
      {{ $tc(`contentNode.laThematicArea.entity.option.${option.translateKey}.name`) }}
    </div>
  </content-node-content>
</template>

<script>
import CheckMark from '../../generic/CheckMark.vue'
import ContentNodeContent from './ContentNodeContent.vue'

export default {
  components: {
    CheckMark,
    ContentNodeContent,
  },
  props: {
    contentNode: { type: Object, required: true },
  },
  computed: {
    selectedOptions() {
      const options = this.contentNode.data.options

      const optionsArray = Object.keys(options).map((key) => ({
        translateKey: key,
        checked: options[key].checked,
      }))

      return optionsArray.filter((item) => item.checked)
    },
  },
}
</script>

// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/LAThematicArea.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text, View } from '@react-pdf/renderer'
import Checkmark from '../../Checkmark.jsx'
import InstanceName from '../InstanceName.jsx'

function LAThematicArea(props) {
  const laThematicArea = props.contentNode
  const options = laThematicArea.data.options
  const optionsArray = Object.keys(options).map((key) => ({
    translateKey: key,
    checked: options[key].checked,
  }))

  return (
    <View style={{ marginBottom: '6pt' }}>
      <InstanceName contentNode={laThematicArea} $tc={props.$tc} />
      {optionsArray
        .filter((option) => option.checked)
        .map((option) => {
          return (
            <View
              style={{ display: 'flex', flexDirection: 'row', alignItems: 'top' }}
              key={option.translateKey}
            >
              <Checkmark size={8} />
              <Text style={{ marginLeft: '2pt' }}>
                {' '}
                {props.$tc(
                  `contentNode.laThematicArea.entity.option.${option.translateKey}.name`
                )}
              </Text>
            </View>
          )
        })}
    </View>
  )
}

export default LAThematicArea
