// pdf/src/campPrint/scheduleEntry/contentNode/LAThematicArea.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <template v-for="(data, key) in contentNode.data.options" :key="key">
      <View v-if="data.checked" class="la-thematic-area-entry">
        <Checkmark :size="8" />
        <Text style="margin-left: 2pt">{{ translation(key) }}</Text>
      </View>
    </template>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import Checkmark from '../../Checkmark.vue'

export default {
  name: 'LAThematicArea',
  components: { InstanceName, Checkmark },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
  methods: {
    translation(key) {
      return this.$tc(`contentNode.laThematicArea.entity.option.${key}.name`)
    },
  },
}
</script>
<pdf-style>
.la-thematic-area-entry {
  display: flex;
  flex-direction: row;
  align-items: top;
}
</pdf-style>

// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/LAThematicArea.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import Checkmark from '../../Checkmark.jsx'
import InstanceName from '../InstanceName.jsx'

function LAThematicArea(props) {
  const laThematicArea = props.contentNode
  const options = laThematicArea.data.options
  const optionsArray = Object.keys(options).map((key) => ({
    translateKey: key,
    checked: options[key].checked,
  }))

  return (
    <View style={{ marginBottom: '6pt' }}>
      <InstanceName contentNode={laThematicArea} $tc={props.$tc} />
      {optionsArray.map((option) => {
        return (
          <View
            style={{ display: 'flex', flexDirection: 'row', alignItems: 'top' }}
            key={option.translateKey}
          >
            <Checkmark size={8} />
            <Text style={{ marginLeft: '2pt' }}>
              {' '}
              {props.$tc(
                `contentNode.laThematicArea.entity.option.${option.translateKey}.name`
              )}
            </Text>
          </View>
        )
      })}
    </View>
  )
}

export default LAThematicArea
