// pdf/src/campPrint/scheduleEntry/contentNode/Material.vue
<template>
  <View class="content-node material">
    <InstanceName :content-node="contentNode" />
    <View
      v-for="item in contentNode.materialItems().items"
      :key="item.id"
      class="material-item"
    >
      <View class="material-item-column material-item-column-1">
        <Text>{{ item.quantity }} {{ item.unit }} {{ item.article }}</Text>
      </View>
      <View class="material-item-column material-item-column-2">
        <Text>{{ item.materialList().name }}</Text>
      </View>
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import InstanceName from '../InstanceName.vue'

export default {
  name: 'Material',
  components: { InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<pdf-style>
.material {
  display: flex;
  flex-direction: column;
}
.material-item {
  display: flex;
  flex-direction: row;
}
.material-item-column {
  flex-grow: 1;
  border-bottom: 1px solid black;
}
.material-item-column-1 {
  flex-basis: 7000pt;
  padding-right: 2pt;
}
.material-item-column-2 {
  flex-basis: 3000pt;
  padding-left: 2pt;
}
</pdf-style>

// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/Material.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text, View } from '@react-pdf/renderer'
import InstanceName from '../InstanceName.jsx'

const columnStyles = {
  flexGrow: '1',
  borderBottom: '1px solid black',
}

const column1Styles = {
  ...columnStyles,
  flexBasis: '7000pt',
  paddingRight: '2pt',
}

const column2Styles = {
  ...columnStyles,
  flexBasis: '3000pt',
  paddingLeft: '2pt',
}

function Material(props) {
  const material = props.contentNode
  const items = material.materialItems().items
  return (
    <View style={{ display: 'flex', flexDirection: 'column', marginBottom: '6pt' }}>
      <InstanceName contentNode={material} $tc={props.$tc} />
      {items.map((item) => {
        return (
          <View key={item.id} style={{ display: 'flex', flexDirection: 'row' }}>
            <View style={column1Styles}>
              <Text>
                {item.quantity} {item.unit} {item.article}
              </Text>
            </View>
            <View style={column2Styles}>
              <Text>{item.materialList().name}</Text>
            </View>
          </View>
        )
      })}
    </View>
  )
}

export default Material
