// pdf/src/campPrint/scheduleEntry/contentNode/Storycontext.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <View style="line-height: 0.8">
      <RichText :rich-text="contentNode.data.html" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'

export default {
  name: 'Storycontext',
  components: { RichText, InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<style lang="react-pdf"></style>

// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/Storycontext.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View } from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'
import InstanceName from '../InstanceName.jsx'

function Storycontext(props) {
  const storycontext = props.contentNode
  return (
    <View style={{ marginBottom: '6pt' }}>
      <InstanceName contentNode={storycontext} $tc={props.$tc} />
      <RichText richText={storycontext.data.text} />
    </View>
  )
}

export default Storycontext
