// frontend/src/components/print/print-react/components/story/StoryDay.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text, View } from '@react-pdf/renderer'
import styles from '../styles.js'
import sortBy from 'lodash/sortBy.js'
import CategoryLabel from '../CategoryLabel.jsx'
import RichText from '../RichText.jsx'
import dayjs from '@/common/helpers/dayjs.js'

function dateLong(dateTimeString, $tc) {
  return dayjs.utc(dateTimeString).format($tc('global.datetime.dateLong'))
}
function isEmptyHtml(html) {
  if (html === null) {
    return true
  }

  return html.trim() === '' || html.trim() === '<p></p>'
}

function StoryDay(props) {
  const sortedScheduleEntries = sortBy(
    props.period.scheduleEntries().items.filter((scheduleEntry) => {
      return scheduleEntry.day()._meta.self === props.day._meta.self
    }),
    (scheduleEntry) => scheduleEntry.start
  )
  const entries = sortedScheduleEntries.map((scheduleEntry) => ({
    scheduleEntry: scheduleEntry,
    storyChapters: props.period
      .contentNodes()
      .items.filter(
        (contentNode) =>
          contentNode.contentTypeName === 'Storycontext' &&
          contentNode.root()._meta.self ===
            scheduleEntry.activity().rootContentNode()._meta.self &&
          !isEmptyHtml(contentNode.data.html)
      ),
  }))
  const entriesWithStory = entries.filter(({ storyChapters }) => storyChapters.length)

  return (
    <React.Fragment>
      <Text
        id={`${props.id}-${props.period.id}-${props.day.id}`}
        style={{ ...styles.h2, marginTop: '12pt' }}
      >
        {props.$tc('entity.day.name')} {props.day.number} (
        {dateLong(props.day.start, props.$tc)})
      </Text>
      {entriesWithStory.map(({ scheduleEntry, storyChapters }) => {
        return (
          <React.Fragment key={scheduleEntry.id}>
            {storyChapters.map((chapter, idx) => {
              const chapterTitle =
                scheduleEntry.activity().title +
                (chapter.instanceName ? ' - ' + chapter.instanceName : '')
              return (
                <React.Fragment key={idx}>
                  <View
                    style={{
                      ...styles.h3,
                      display: 'flex',
                      flexDirection: 'row',
                      marginTop: '10pt',
                    }}
                    minPresenceAhead={30}
                  >
                    <Text id={`${props.id}-${props.period.id}-${scheduleEntry.id}`}>
                      {scheduleEntry.number}{' '}
                    </Text>
                    <CategoryLabel activity={scheduleEntry.activity()} />
                    <Text> {chapterTitle}</Text>
                  </View>
                  <RichText richText={chapter.data.html} />
                </React.Fragment>
              )
            })}
          </React.Fragment>
        )
      })}
    </React.Fragment>
  )
}

export default StoryDay

// frontend/src/components/camp/StoryDay.vue
<template>
  <div>
    <h3>{{ dayName }}</h3>
    <template v-if="entriesWithStory.length">
      <div v-for="{ scheduleEntry, storyChapters } in entriesWithStory" :key="scheduleEntry._meta.uri">
        <h4>{{ scheduleEntry.activity().title }}</h4>
        <template v-if="editing">
          <api-form v-for="chapter in storyChapters" :key="chapter._meta.uri" :entity="chapter">
            <api-textarea
              fieldname="text"
              label=""
              auto-grow
              :outlined="false"
              :solo="false" />
          </api-form>
        </template>
        <template v-else>
          <tiptap-editor v-for="chapter in storyChapters" :key="chapter._meta.uri" :value="chapter.text" />
        </template>
      </div>
    </template>
    <div v-else class="grey--text">
      {{ $tc('components.camp.storyDay.noStory') }}
    </div>
  </div>
</template>
<script>
import { sortBy } from 'lodash'
import ApiForm from '@/components/form/api/ApiForm'
import ApiTextarea from '@/components/form/api/ApiTextarea'
import TiptapEditor from '@/components/form/tiptap/TiptapEditor'

export default {
  name: 'StoryDay',
  components: { TiptapEditor, ApiForm, ApiTextarea },
  props: {
    day: { type: Object, required: true }
  },
  data () {
    return {
      editing: false
    }
  },
  computed: {
    dayName () {
      const date = this.addDays(this.day.period().start, this.day.dayOffset)
      return this.$moment.utc(date).format(this.$tc('global.moment.dateLong'))
    },
    sortedScheduleEntries () {
      return sortBy(this.day.scheduleEntries().items, scheduleEntry => scheduleEntry.periodOffset)
    },
    entries () {
      return this.sortedScheduleEntries.map(scheduleEntry => {
        return {
          scheduleEntry: scheduleEntry,
          storyChapters: (scheduleEntry.activity().activityContents() || { items: [] })
            .items
            .filter(activityContent => activityContent.contentTypeName === 'Storycontext')
            .map(activityContent => activityContent.singleText())
            .filter(text => text.text)
        }
      })
    },
    entriesWithStory () {
      return this.entries.filter(({ storyChapters }) => storyChapters.length)
    }
  },
  methods: {
    addDays (date, days) {
      return Date.parse(date) + days * 24 * 60 * 60 * 1000
    }
  }
}
</script>
