// frontend/src/components/print/print-react/components/picasso/ScheduleEntry.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '../../reactPdf.js'
import Responsibles from './Responsibles.jsx'

const fontSize = 8

function scheduleEntryTitle(scheduleEntry) {
  return (
    scheduleEntry.activity().category().short +
    ' ' +
    scheduleEntry.number +
    ' ' +
    scheduleEntry.activity().title
  )
}

const scheduleEntryStyles = {
  position: 'absolute',
  borderRadius: '2px',
  padding: '0 4px',
  flexDirection: 'column',
  justifyContent: 'flex-start',
}

const titleStyles = {
  fontSize: fontSize + 'pt',
  flexShrink: '0',
}

const responsiblesContainerStyle = {
  position: 'absolute',
  top: '0',
  bottom: '0',
  right: '0',
  left: '0',
  flexDirection: 'column',
  alignItems: 'flex-end',
  justifyContent: 'flex-end',
  padding: '0 4px',
}

const responsiblesStyle = {
  flexShrink: '0',
}

const spacerStyles = {
  height: '4px',
  flexShrink: '1',
}

function ScheduleEntry({ scheduleEntry, styles }) {
  return (
    <View
      style={{
        left: scheduleEntry.left * 100 + '%',
        right: (1.0 - scheduleEntry.left - scheduleEntry.width) * 100 + '%',
        backgroundColor: scheduleEntry.activity().category().color,
        ...scheduleEntryStyles,
        ...styles,
      }}
    >
      <View style={spacerStyles} />
      <Text style={titleStyles}>{scheduleEntryTitle(scheduleEntry)}</Text>
      <View style={spacerStyles} />
      <View style={responsiblesContainerStyle}>
        <View style={spacerStyles} />
        <Responsibles styles={responsiblesStyle} activity={scheduleEntry.activity()} />
        <View style={spacerStyles} />
      </View>
    </View>
  )
}

export default ScheduleEntry

// pdf/src/campPrint/picasso/ScheduleEntry.vue
<template>
  <View class="picasso-schedule-entry" :style="{ backgroundColor: color }">
    <View class="picasso-schedule-entry-spacer" />
    <Text class="picasso-schedule-entry-title">
      {{ category }} {{ scheduleEntry.number }} {{ title }}
    </Text>
    <View class="picasso-schedule-entry-spacer" />
    <View class="picasso-schedule-entry-responsibles-container">
      <View class="picasso-schedule-entry-spacer" />
      <Responsibles
        class="picasso-schedule-entry-responsibles"
        :activity="scheduleEntry.activity()"
      />
      <View class="picasso-schedule-entry-spacer" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import Responsibles from './Responsibles.vue'
import { contrastColor } from '@/common/helpers/colors.js'

export default {
  name: 'ScheduleEntry',
  components: { Responsibles },
  extends: PdfComponent,
  props: {
    scheduleEntry: { type: Object, required: true },
  },
  computed: {
    color() {
      return this.scheduleEntry.activity().category().color
    },
    textColor() {
      return contrastColor(this.color)
    },
    category() {
      return this.scheduleEntry.activity().category().short
    },
    title() {
      return this.scheduleEntry.activity().title
    },
  },
}
</script>
<pdf-style>
.picasso-schedule-entry {
  position: absolute;
  padding: 0 4pt;
  flex-direction: column;
  justify-content: flex-start;
}
.picasso-schedule-entry-spacer {
  height: 0;
  max-height: 4pt;
  flex-grow: 1;
}
.picasso-schedule-entry-title {
  fontSize: 8pt;
  height: 16pt;
  line-height: 1;
  flex-grow: 1;
}
.picasso-schedule-entry-responsibles-container {
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  flex-direction: column;
  align-items: flex-end;
  justify-content: flex-end;
  padding: 0 4pt;
}
</pdf-style>
