// frontend/src/components/print/components/scheduleEntry/contentNode/Material.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '../../../reactPdf.js'

const columnStyles = {
  flexGrow: '1',
  borderBottom: '1px solid black'
}

const column1Styles = {
  ...columnStyles,
  flexBasis: '7000pt',
  paddingRight: '2pt'
}

const column2Styles = {
  ...columnStyles,
  flexBasis: '3000pt',
  paddingLeft: '2pt'
}

function Material (props) {
  const material = props.contentNode
  const items = material.materialItems().items
  return <View style={{ display: 'flex', flexDirection: 'column', marginBottom: '6pt' }}>
    <Text style={{ fontWeight: 'bold', borderBottom: '1px solid black' }}>{ material.instanceName || props.$tc('contentNode.material.name') }</Text>
    { items.map(item => {
      return <View key={item.id} style={{ display: 'flex', flexDirection: 'row' }}>
        <View style={column1Styles}>
          <Text>{item.quantity} {item.unit} {item.article}</Text>
        </View>
        <View style={column2Styles}>
          <Text>{item.materialList().name}</Text>
        </View>
      </View>
    }) }
  </View>
}

export default Material

// print/components/scheduleEntry/contentNode/Material.vue
<template>
  <div class="wrapper">
    <div class="instance-name">{{ instanceName }}</div>
    <div v-for="item in items" :key="item.id" class="item">
      <div class="material-row">
        <div class="item">
          {{ item.quantity }} {{ item.unit }} {{ item.article }}
        </div>
        <div class="list-name">{{ item.materialList().name }}</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    contentNode: { type: Object, required: true },
  },
  async fetch() {
    await this.contentNode.materialItems().$loadItems()
  },
  computed: {
    instanceName() {
      return (
        this.contentNode.instanceName || this.$tc(`contentNode.material.name`)
      )
    },
    items() {
      return this.contentNode.materialItems().items
    },
  },
}
</script>

<style scoped lang="scss">
.instance-name {
  font-weight: bold;
}
.material-row {
  display: flex;
  flex-direction: row;
}
.item {
  flex-basis: 7000px;
  padding-right: 4px;
}
.list-name {
  flex-basis: 3000px;
  padding-left: 4px;
}
</style>
