// frontend/src/pdf/campPrint/cover/Cover.vue
<template>
  <Page
    :id="id"
    :size="config.options.pageSize || 'A4'"
    :bookmark="$tc('print.cover.title')"
    class="page"
  >
    <TocSectionStartMarker :id="id" />
    <View class="cover-camp-wrapper">
      <Text v-if="config.camp.organizer" class="cover-camp-organizer cover-center">
        {{ config.camp.organizer }}
      </Text>
      <Text class="cover-camp-title cover-center">{{ config.camp.title }}</Text>
      <Text class="cover-camp-motto cover-center">
        {{ config.camp.motto }}
      </Text>
    </View>
  </Page>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import TocSectionStartMarker from '../TocSectionStartMarker.vue'

export default {
  name: 'Cover',
  components: { TocSectionStartMarker },
  extends: PdfComponent,
  props: {
    content: { type: Object, required: true },
    config: { type: Object, required: true },
  },
}
</script>
<style lang="react-pdf">
.cover-center {
  text-align: center;
}
.cover-camp-wrapper {
  padding: 72pt 0 0;
}
.cover-camp-organizer {
  font-size: 18pt;
  font-weight: 600;
}
.cover-camp-title {
  font-size: 38pt;
  font-weight: 600;
  margin: 40pt 0;
}
.cover-camp-motto {
  font-size: 28pt;
  font-weight: 500;
}
</style>

// frontend/src/components/print/print-react/components/cover/Cover.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Page, Text } from '@react-pdf/renderer'
import styles from '../styles.js'

function Cover(props) {
  const camp = props.store.get(props.config.camp._meta.self)
  return (
    <Page
      id={props.id}
      bookmark={props.$tc('components.cover.title')}
      style={styles.page}
    >
      <Text style={{ textAlign: 'center', margin: '40pt 0', fontSize: '40pt' }}>
        {camp.title}
      </Text>
      <Text style={{ fontSize: '20pt', marginBottom: '25pt', textAlign: 'center' }}>
        <Text style={{ fontWeight: 'bold' }}>
          {props.$tc('entity.camp.fields.title')}:{' '}
        </Text>
        {camp.title}
      </Text>
      <Text style={{ fontSize: '20pt', marginBottom: '25pt', textAlign: 'center' }}>
        <Text style={{ fontWeight: 'bold' }}>
          {props.$tc('entity.camp.fields.motto')}:{' '}
        </Text>
        {camp.motto}
      </Text>
    </Page>
  )
}

export default Cover
