// pdf/src/campPrint/cover/Cover.vue
<template>
  <Page :id="id" size="A4" :bookmark="$tc('print.cover.title')" class="page">
    <Text class="cover-camp-name">{{ config.camp.name }}</Text>
    <Text class="cover-camp-metadata">
      <Text style="font-weight: bold">{{ $tc('entity.camp.fields.title') }}: </Text>
      {{ config.camp.title }}
    </Text>
    <Text class="cover-camp-metadata">
      <Text style="font-weight: bold">{{ $tc('entity.camp.fields.motto') }}: </Text>
      {{ config.camp.motto }}
    </Text>
  </Page>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'

export default {
  name: 'Cover',
  extends: PdfComponent,
  props: {
    content: { type: Object, required: true },
    config: { type: Object, required: true },
  },
}
</script>
<pdf-style>
.cover-camp-name {
  text-align: center;
  margin: 40pt 0;
  font-size: 40pt;
}
.cover-camp-metadata {
  text-align: center;
  margin-bottom: 25pt;
  font-size: 20pt;
}
</pdf-style>

// frontend/src/components/print/print-react/components/cover/Cover.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Page, Text } from '@react-pdf/renderer'
import styles from '../styles.js'

function Cover(props) {
  const camp = props.store.get(props.config.camp._meta.self)
  return (
    <Page id={props.id} bookmark={props.$tc('print.cover.title')} style={styles.page}>
      <Text style={{ textAlign: 'center', margin: '40pt 0', fontSize: '40pt' }}>
        {camp.title}
      </Text>
      <Text style={{ fontSize: '20pt', marginBottom: '25pt', textAlign: 'center' }}>
        <Text style={{ fontWeight: 'bold' }}>
          {props.$tc('entity.camp.fields.title')}:{' '}
        </Text>
        {camp.title}
      </Text>
      <Text style={{ fontSize: '20pt', marginBottom: '25pt', textAlign: 'center' }}>
        <Text style={{ fontWeight: 'bold' }}>
          {props.$tc('entity.camp.fields.motto')}:{' '}
        </Text>
        {camp.motto}
      </Text>
    </Page>
  )
}

export default Cover
