// pdf/src/campPrint/scheduleEntry/InstanceName.vue
<template>
  <Text class="content-node-instance-name">{{ instanceName }}</Text>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import camelCase from 'lodash/camelCase.js'

export default {
  name: 'InstanceName',
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
  computed: {
    instanceName() {
      return (
        this.contentNode.instanceName ||
        this.$tc(`contentNode.${camelCase(this.contentNode.contentTypeName)}.name`)
      )
    },
  },
}
</script>
<pdf-style>
.content-node-instance-name {
  font-weight: bold;
}
</pdf-style>

// frontend/src/components/print/print-react/components/scheduleEntry/InstanceName.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text } from '@react-pdf/renderer'
import camelCase from 'lodash/camelCase.js'

function InstanceName({ contentNode, $tc }) {
  return (
    <Text style={{ fontWeight: 'bold' }}>
      {contentNode.instanceName ||
        $tc(`contentNode.${camelCase(contentNode.contentTypeName)}.name`)}
    </Text>
  )
}

export default InstanceName
