// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/Notes.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View } from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'
import InstanceName from '../InstanceName.jsx'

function Notes(props) {
  const notes = props.contentNode
  return (
    <View style={{ marginBottom: '6pt' }}>
      <InstanceName contentNode={notes} $tc={props.$tc} />
      <RichText richText={notes.data.html} />
    </View>
  )
}

export default Notes

// pdf/src/campPrint/scheduleEntry/contentNode/Notes.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <View style="line-height: 1.4">
      <RichText :rich-text="contentNode.data.html" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'

export default {
  name: 'Notes',
  components: { RichText, InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<pdf-style>
</pdf-style>
