// frontend/src/components/print/scheduleEntry/contentNode/SafetyConcept.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'

const { View, Text } = pdf

function SafetyConcept (props) {
  const safetyConcept = props.contentNode
  return <View style={{ marginBottom: '6pt' }}>
    { safetyConcept.instanceName ? <Text style={{ fontWeight: 'bold' }}>{ safetyConcept.instanceName }</Text> : <View/> }
    <RichText richText={safetyConcept.text}/>
  </View>
}

export default SafetyConcept

// pdf/src/campPrint/scheduleEntry/contentNode/SafetyConcept.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <View style="line-height: 1.4">
      <RichText :rich-text="contentNode.data.html" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'

export default {
  name: 'SafetyConcept',
  components: { RichText, InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<pdf-style>
</pdf-style>
