// frontend/src/components/print/print-react/components/CategoryLabel.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text } from '@react-pdf/renderer'
import styles from './styles.js'
import { contrastColor } from '@/common/helpers/colors.js'

function textColor(color) {
  return contrastColor(color)
}

function CategoryLabel({ category, style }) {
  return (
    <Text
      style={{
        ...styles.categoryLabel,
        color: textColor(category.color),
        backgroundColor: category.color,
        ...style,
      }}
    >
      {category.short}
    </Text>
  )
}

export default CategoryLabel

// frontend/src/pdf/campPrint/CategoryLabel.vue
<template>
  <Text class="category-label" :style="{ color, backgroundColor }">
    {{ category.short }}
  </Text>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import { contrastColor } from '../../common/helpers/colors.js'

export default {
  name: 'CategoryLabel',
  extends: PdfComponent,
  props: {
    category: { type: Object, required: true },
  },
  computed: {
    backgroundColor() {
      return this.category.color
    },
    color() {
      return contrastColor(this.backgroundColor)
    },
  },
}
</script>
<style lang="react-pdf">
.category-label {
  padding: 2pt 8pt;
  border-radius: 18pt;
  align-self: center;
}
</style>
