// frontend/src/components/print/components/scheduleEntry/contentNode/LAThematicArea.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '../../../reactPdf.js'
import camelCase from 'lodash/camelCase.js'
import Checkmark from '../../Checkmark.jsx'

function LAThematicArea (props) {
  const laThematicArea = props.contentNode
  const options = laThematicArea.options().items.filter(item => item.checked)
  return <View style={{ marginBottom: '6pt' }}>
    <Text style={{ fontWeight: 'bold' }}>{ laThematicArea.instanceName || props.$tc(`contentNode.${camelCase(laThematicArea.contentTypeName)}.name`) }</Text>
    { options.map(option => {
      return <View style={{ display: 'flex', flexDirection: 'row', alignItems: 'top' }} key={option.id}>
        <Checkmark size={8}/><Text style={{ marginLeft: '2pt' }}> { props.$tc(`contentNode.laThematicArea.entity.option.${option.translateKey}.name`) }</Text>
      </View>
    }) }
  </View>
}

export default LAThematicArea

// frontend/src/pdf/campPrint/scheduleEntry/contentNode/LAThematicArea.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <template v-for="(data, key) in contentNode.data.options">
      <View v-if="data.checked" class="la-thematic-area-entry">
        <Checkmark :size="8" />
        <Text style="margin-left: 2pt">{{ translation(key) }}</Text>
      </View>
    </template>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import Checkmark from '../../Checkmark.vue'

export default {
  name: 'LAThematicArea',
  components: { InstanceName, Checkmark },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
  methods: {
    translation(key) {
      return this.$tc(`contentNode.laThematicArea.entity.option.${key}.name`)
    },
  },
}
</script>
<style lang="react-pdf">
.la-thematic-area-entry {
  display: flex;
  flex-direction: row;
  align-items: top;
}
</style>
