// frontend/src/components/print/components/scheduleEntry/contentNode/Storycontext.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'

const { View, Text } = pdf

function Storycontext (props) {
  const storycontext = props.contentNode
  return <View style={{ marginBottom: '6pt' }}>
    { storycontext.instanceName ? <Text style={{ fontWeight: 'bold' }}>{ storycontext.instanceName }</Text> : <View/> }
    <RichText richText={storycontext.text}/>
  </View>
}

export default Storycontext

// frontend/src/pdf/campPrint/scheduleEntry/contentNode/Storycontext.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <View style="line-height: 0.8">
      <RichText :rich-text="contentNode.data.html" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'

export default {
  name: 'Storycontext',
  components: { RichText, InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<style lang="react-pdf"></style>
