// frontend/src/components/print/print-react/components/scheduleEntry/contentNode/Storyboard.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'
import InstanceName from '../InstanceName.jsx'

const columnStyles = {
  flexGrow: '1',
  lineHeight: 1.6,
  paddingBottom: '4pt',
}

const column1Styles = {
  ...columnStyles,
  flexBasis: '23pt',
  flexShrink: '0',
  flexGrow: '0',
  paddingRight: '2pt',
  overflow: 'hidden',
}

const column2Styles = {
  ...columnStyles,
  flexBasis: 0,
  flexGrow: '1',
  borderLeft: '1px solid black',
  paddingHorizontal: '2pt',
}

const column3Styles = {
  ...columnStyles,
  flexBasis: '40pt',
  flexShrink: '0',
  flexGrow: '0',
  borderLeft: '1px solid black',
  paddingLeft: '2pt',
  overflow: 'hidden',
}

function Storyboard(props) {
  const storyboard = props.contentNode
  const sections = storyboard.data.sections
  const sectionsArray = Object.keys(sections).map((key) => ({
    key,
    column1: sections[key].column1,
    column2: sections[key].column2,
    column3: sections[key].column3,
    position: sections[key].position,
  }))
  return (
    <View style={{ display: 'flex', flexDirection: 'column', marginBottom: '6pt' }}>
      <InstanceName contentNode={storyboard} $tc={props.$tc} />
      <View
        style={{
          display: 'flex',
          flexDirection: 'row',
          borderBottom: '1px solid black',
        }}
      >
        <View style={{ ...column1Styles, paddingBottom: 0 }}>
          <Text>{props.$tc('contentNode.storyboard.entity.section.fields.column1')}</Text>
        </View>
        <View style={{ ...column2Styles, paddingBottom: 0 }}>
          <Text>{props.$tc('contentNode.storyboard.entity.section.fields.column2')}</Text>
        </View>
        <View style={{ ...column3Styles, paddingBottom: 0 }}>
          <Text>{props.$tc('contentNode.storyboard.entity.section.fields.column3')}</Text>
        </View>
      </View>
      {sectionsArray
        .sort((section1, section2) => section1.position - section2.position)
        .map((section) => {
          return (
            <View key={section.key} style={{ display: 'flex', flexDirection: 'row' }}>
              <View style={column1Styles}>
                <Text>{section.column1}</Text>
              </View>
              <View style={column2Styles}>
                <RichText richText={section.column2} />
              </View>
              <View style={column3Styles}>
                <Text>{section.column3}</Text>
              </View>
            </View>
          )
        })}
    </View>
  )
}

export default Storyboard

// frontend/src/pdf/campPrint/scheduleEntry/contentNode/Storyboard.vue
<template>
  <View class="content-node storyboard-container">
    <InstanceName :content-node="contentNode" />
    <View v-if="anyContent" class="storyboard-header-row">
      <View class="storyboard-header-cell storyboard-column-1">
        <Text>{{ $tc('contentNode.storyboard.entity.section.fields.column1') }}</Text>
      </View>
      <View class="storyboard-header-cell storyboard-column-2">
        <Text>{{ $tc('contentNode.storyboard.entity.section.fields.column2Html') }}</Text>
      </View>
      <View class="storyboard-header-cell storyboard-column-3">
        <Text>{{ $tc('contentNode.storyboard.entity.section.fields.column3') }}</Text>
      </View>
    </View>
    <View v-for="section in sections" class="storyboard-row">
      <View class="storyboard-cell storyboard-column-1">
        <Text>{{ section.column1 }}</Text>
      </View>
      <View class="storyboard-cell storyboard-column-2">
        <RichText :rich-text="section.column2Html" />
      </View>
      <View class="storyboard-cell storyboard-column-3">
        <Text>{{ section.column3 }}</Text>
      </View>
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'
import sortBy from 'lodash-es/sortBy.js'
import { isEmptyHtml } from '../../helpers.js'

export default {
  name: 'Storyboard',
  components: { InstanceName, RichText },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
  computed: {
    sections() {
      const sections = this.contentNode.data.sections
      return sortBy(
        Object.keys(sections).map((key) => ({
          key,
          column1: sections[key].column1,
          column2Html: sections[key].column2Html,
          column3: sections[key].column3,
          position: sections[key].position,
        })),
        (section) => section.position
      )
    },
    anyContent() {
      return (
        this.sections.length &&
        (this.sections[0].column1.length ||
          !isEmptyHtml(this.sections[0].column2Html) ||
          this.sections[0].column3.length)
      )
    },
  },
}
</script>
<style lang="react-pdf">
.storyboard-container {
  display: flex;
  flex-direction: column;
}
.storyboard-header-row {
  display: flex;
  flex-direction: row;
  border-bottom: 0.75pt solid #94A3B8;
}
.storyboard-row {
  display: flex;
  flex-direction: row;
}
.storyboard-header-cell {
  line-height: 0.8;
  font-weight: 600;
}
.storyboard-cell {
  line-height: 0.8;
  padding-top: 1pt;
  padding-bottom: 3pt;
}
.storyboard-column-1 {
  width: 28pt;
  flex-shrink: 0;
  flex-grow: 0;
  padding-right: 2pt;
  overflow: hidden;
}
.storyboard-column-2 {
  flex-basis: 0;
  flex-grow: 1;
  border-left: 0.75pt solid #94A3B8;
  padding-horizontal: 2pt;
}
.storyboard-column-3 {
  flex-basis: 40pt;
  flex-shrink: 0;
  flex-grow: 0;
  border-left: 0.75pt solid #94A3B8;
  padding-left: 2pt;
  overflow: hidden;
}
</style>
