// pdf/src/campPrint/picasso/DayHeader.vue
<template>
  <View>
    <Text class="picasso-day-header-text">{{ date }}</Text>
    <View v-if="showDayResponsibles" class="picasso-day-responsibles">
      <Text>{{ dayResponsibles }}</Text>
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import {
  dayResponsiblesCommaSeparated,
  filterDayResponsiblesByDay,
} from '../../../common/helpers/dayResponsibles.js'

export default {
  name: 'DayHeader',
  extends: PdfComponent,
  props: {
    day: { type: Object, required: true },
    showDayResponsibles: { type: Boolean, default: false },
  },
  computed: {
    date() {
      return this.$date.utc(this.day.start).hour(0).minute(0).second(0).format('ddd LL')
    },
    dayResponsibles() {
      if (filterDayResponsiblesByDay(this.day).length === 0) return ''
      const label = this.$tc('entity.day.fields.dayResponsibles')
      const displayNames = dayResponsiblesCommaSeparated(this.day, this.$tc)
      return `${label}: ${displayNames}`
    },
  },
}
</script>
<pdf-style>
.picasso-day-header-text {
  font-size: 8pt;
  font-weight: bold;
  margin: 0 auto 2pt;
}
.picasso-day-responsibles {
  font-size: 8pt;
  margin: 3pt auto 0;
}
</pdf-style>

// frontend/src/components/print/picasso/DayHeader.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import dayjs from '../../../../../common/helpers/dayjs.js'

const { View, Text } = pdf

const wrapperStyles = {
  flexGrow: '1',
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
  padding: '4pt 0 2pt'
}

const textStyles = {
  fontSize: '9pt',
  margin: '0 auto'
}

function renderDate (day) {
  return dayjs.utc(day.start).hour(0).minute(0).second(0).format('ddd LL')
}

function DayHeader ({ day, styles }) {
  return <View style={{ ...wrapperStyles, ...styles }}>
    <Text style={ textStyles }>{ renderDate(day) }</Text>
  </View>
}

export default DayHeader
