// print/components/scheduleEntry/contentNode/ContentNode.vue
<template>
  <div>
    <component
      :is="componentFor(contentNode)"
      :content-node="contentNode"
    ></component>
  </div>
</template>

<script>
import NotImplemented from './NotImplemented.vue'
import ColumnLayout from './ColumnLayout.vue'
import LAThematicArea from './LAThematicArea.vue'
import Material from './Material.vue'
import Notes from './Notes.vue'
import SafetyConcept from './SafetyConcept.vue'
import Storycontext from './Storycontext.vue'
import Storyboard from './Storyboard.vue'

export default {
  components: {
    NotImplemented,
    ColumnLayout,
    LAThematicArea,
    Material,
    Notes,
    SafetyConcept,
    Storyboard,
    Storycontext,
  },
  props: {
    contentNode: { type: Object, required: true },
  },
  async fetch() {
    await Promise.all([
      this.contentNode._meta.load,
      this.contentNode.children().$loadItems(),
      this.contentNode.contentType()._meta.load,
    ])
  },
  methods: {
    componentFor(contentNode) {
      const contentTypeName = contentNode.contentType().name
      if (contentTypeName in this.$options.components) {
        return contentTypeName
      }
      return 'NotImplemented'
    },
  },
}
</script>

// frontend/src/components/print/components/scheduleEntry/contentNode/ContentNode.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text } from '../../../reactPdf.js'
import ColumnLayout from './ColumnLayout.jsx'
import LAThematicArea from './LAThematicArea.jsx'
import Storyboard from './Storyboard.jsx'
import Notes from './Notes.jsx'
import SafetyConcept from './SafetyConcept.jsx'
import Material from './Material.jsx'
import Storycontext from './Storycontext.jsx'

const contentNodeComponents = {
  ColumnLayout,
  LAThematicArea,
  Storyboard,
  Notes,
  SafetyConcept,
  Material,
  Storycontext
}

function ContentNode (props) {
  const contentTypeName = props.contentNode.contentType().name
  if (typeof contentNodeComponents[contentTypeName] !== 'undefined') {
    return React.createElement(contentNodeComponents[contentTypeName], { ...props, ContentNode })
  } else {
    return <Text>{contentTypeName}</Text>
  }
}

export default ContentNode
