// frontend/src/pdf/campPrint/scheduleEntry/contentNode/Notes.vue
<template>
  <View class="content-node">
    <InstanceName :content-node="contentNode" />
    <View style="line-height: 0.8">
      <RichText :rich-text="contentNode.data.html" />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import InstanceName from '../InstanceName.vue'
import RichText from '../../RichText.vue'

export default {
  name: 'Notes',
  components: { RichText, InstanceName },
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
}
</script>
<style lang="react-pdf"></style>

// frontend/src/components/print/components/scheduleEntry/contentNode/Notes.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import RichText from '../../RichText.jsx'

const { View, Text } = pdf

function Notes (props) {
  const notes = props.contentNode
  return <View style={{ marginBottom: '6pt' }}>
    { notes.instanceName ? <Text style={{ fontWeight: 'bold' }}>{ notes.instanceName }</Text> : <View/> }
    <RichText richText={notes.text}/>
  </View>
}

export default Notes
