// print/components/scheduleEntry/contentNode/Storyboard.vue
<template>
  <div class="wrapper">
    <div v-if="instanceName" class="instance-name">{{ instanceName }}</div>
    <div class="storyboard-row">
      <div class="column column1 header">
        {{ $tc('contentNode.storyboard.entity.section.fields.column1') }}
      </div>
      <div class="column column2 header">
        {{ $tc('contentNode.storyboard.entity.section.fields.column2') }}
      </div>
      <div class="column column3 header">
        {{ $tc('contentNode.storyboard.entity.section.fields.column3') }}
      </div>
    </div>
    <div v-for="section in sections" :key="section.id" class="storyboard-row">
      <div class="column column1">
        <rich-text :rich-text="section.column1" />
      </div>
      <div class="column column2">
        <rich-text :rich-text="section.column2" />
      </div>
      <div class="column column3">
        <rich-text :rich-text="section.column3" />
      </div>
    </div>
  </div>
</template>

<script>
import RichText from '../../RichText.vue'

export default {
  components: {
    RichText,
  },
  props: {
    contentNode: { type: Object, required: true },
  },
  async fetch() {
    await this.contentNode.sections().$loadItems()
  },
  computed: {
    instanceName() {
      return this.contentNode.instanceName
    },
    sections() {
      return this.contentNode
        .sections()
        .items.sort(
          (section1, section2) => section1.position - section2.position
        )
    },
  },
}
</script>

<style scoped lang="scss">
.wrapper {
  margin-bottom: 12px;
}

.instance-name {
  font-weight: bold;
}

.storyboard-row {
  display: flex;
  flex-direction: row;
}

.header {
  padding-bottom: 0;
  border-bottom: 1px solid black;
}

.column {
  flex-grow: 1;
  line-height: 1.6;
  padding-bottom: 8px;
}

.column1 {
  flex-basis: 26px;
  flex-shrink: 0;
  flex-grow: 0;
  padding-right: 4px;
}

.column2 {
  flex-grow: 1;
  border-left: 1px solid black;
  padding-left: 4px;
  padding-right: 4px;
}

.column3 {
  flex-basis: 80px;
  flex-shrink: 0;
  flex-grow: 0;
  border-left: 1px solid black;
  padding-left: 4px;
}
</style>

// frontend/src/components/print/components/scheduleEntry/contentNode/Storyboard.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '../../../reactPdf.js'
import RichText from '../../RichText.jsx'

const columnStyles = {
  flexGrow: '1',
  lineHeight: 1.6,
  paddingBottom: '4pt'
}

const column1Styles = {
  ...columnStyles,
  flexBasis: '23pt',
  flexShrink: '0',
  flexGrow: '0',
  paddingRight: '2pt'
}

const column2Styles = {
  ...columnStyles,
  flexGrow: '1',
  borderLeft: '1px solid black',
  paddingHorizontal: '2pt'
}

const column3Styles = {
  ...columnStyles,
  flexBasis: '40pt',
  flexShrink: '0',
  flexGrow: '0',
  borderLeft: '1px solid black',
  paddingLeft: '2pt'
}

function Storyboard (props) {
  const storyboard = props.contentNode
  const sections = storyboard.sections().items
  return <View style={{ display: 'flex', flexDirection: 'column', marginBottom: '6pt' }}>
    { storyboard.instanceName ? <Text style={{ fontWeight: 'bold' }}>{ storyboard.instanceName }</Text> : <View/> }
    <View style={{ display: 'flex', flexDirection: 'row', borderBottom: '1px solid black' }}>
      <View style={{ ...column1Styles, paddingBottom: 0 }}>
        <Text>{ props.$tc('contentNode.storyboard.entity.section.fields.column1') }</Text>
      </View>
      <View style={{ ...column2Styles, paddingBottom: 0 }}>
        <Text>{ props.$tc('contentNode.storyboard.entity.section.fields.column2') }</Text>
      </View>
      <View style={{ ...column3Styles, paddingBottom: 0 }}>
        <Text>{ props.$tc('contentNode.storyboard.entity.section.fields.column3') }</Text>
      </View>
    </View>
    { sections.sort((section1, section2) => section1.position - section2.position).map(section => {
      return <View key={section.id} style={{ display: 'flex', flexDirection: 'row' }}>
        <View style={column1Styles}>
          <RichText richText={section.column1}/>
        </View>
        <View style={column2Styles}>
          <RichText richText={section.column2}/>
        </View>
        <View style={column3Styles}>
          <RichText richText={section.column3}/>
        </View>
      </View>
    }) }
  </View>
}

export default Storyboard
