// frontend/src/components/print/print-react/components/tableOfContents/entry/Picasso.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Picasso(props) {
  return props.entry.options.periods.map((periodUri) => {
    const period = props.store.get(periodUri)
    return (
      <Link style={tocStyles.entry} href={`#${props.id}-${period.id}`} key={period.id}>
        <Text>{props.$tc('print.picasso.title', { period: period.description })}</Text>
      </Link>
    )
  })
}

export default Picasso

// frontend/src/pdf/campPrint/tableOfContents/entry/Picasso.vue
<template>
  <Link v-for="period in periods" class="toc-entry" :href="`#${id}-${period.id}`">
    <Text>{{ $tc('print.picasso.title', { period: period.description }) }}</Text>
    <TocEntryPageNumber v-if="config.options.pageNumbers" :id="`${id}-${period.id}`" />
  </Link>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import TocEntryPageNumber from '../TocEntryPageNumber.vue'

export default {
  name: 'Picasso',
  components: { TocEntryPageNumber },
  extends: PdfComponent,
  props: {
    entry: { type: Object, required: true },
    config: { type: Object, required: true },
  },
  computed: {
    periods() {
      return this.entry.options.periods.map((periodUri) => this.api.get(periodUri))
    },
  },
}
</script>
<style lang="react-pdf"></style>
