// frontend/src/components/print/print-react/components/tableOfContents/entry/Story.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Story(props) {
  return props.entry.options.periods.map((periodUri) => {
    const period = props.store.get(periodUri)
    return (
      <Link style={tocStyles.entry} href={`#${props.id}-${period.id}`}>
        <Text>
          {props.$tc('print.story.title')}: {period.description}
        </Text>
      </Link>
    )
  })
}

export default Story

// frontend/src/pdf/campPrint/tableOfContents/entry/Story.vue
<template>
  <Link v-for="period in periods" class="toc-entry" :href="`#${id}-${period.id}`">
    <Text>{{ $tc('print.story.title') }}: {{ period.description }}</Text>
    <TocEntryPageNumber v-if="config.options.pageNumbers" :id="`${id}-${period.id}`" />
  </Link>
</template>
<script>
import Summary from './Summary.vue'
import TocEntryPageNumber from '../TocEntryPageNumber.vue'

export default {
  name: 'Story',
  components: { TocEntryPageNumber },
  extends: Summary,
}
</script>
