// frontend/src/components/print/print-react/components/picasso/DayColumn.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View } from '../../reactPdf.js'
import ScheduleEntry from './ScheduleEntry.jsx'
import dayjs from '@/common/helpers/dayjs.js'

// converts ISO String format (UTC timezone) into a unix/seconds timestamp (UTC timezone)
function stringToTimestamp(string) {
  return dayjs.utc(string).unix()
}

function getWeightsSum(times) {
  return times.reduce((sum, [_, weight]) => sum + weight, 0)
}

function percentage(seconds, times) {
  const hours = seconds / 3600.0
  let matchingTimeIndex = times.findIndex(([time, _]) => time >= hours)
  matchingTimeIndex = Math.min(
    matchingTimeIndex < 0 ? times.length : matchingTimeIndex,
    times.length - 1
  )
  const remainder = hours - times[matchingTimeIndex][0]
  const weightsSum =
    getWeightsSum(times.slice(0, matchingTimeIndex)) +
    remainder * times[Math.min(matchingTimeIndex, times.length)][1]
  const totalWeightsSum = getWeightsSum(times)
  if (totalWeightsSum === 0) {
    return 0
  }
  const result = (weightsSum * 100.0) / totalWeightsSum
  return Math.max(0, Math.min(100, result))
}

function dayBoundariesInMinutes(day, times) {
  const [dayStart] = times[0]
  const [dayEnd] = times[times.length - 1]

  const dayStartTimestamp = stringToTimestamp(day.start)

  const dayStartMinutes = dayStartTimestamp + dayStart * 3600
  const dayEndMinutes = dayStartTimestamp + dayEnd * 3600

  return [dayStartMinutes, dayEndMinutes]
}

function filterScheduleEntriesByDay(scheduleEntries, day, times) {
  const [dayStart, dayEnd] = dayBoundariesInMinutes(day, times)

  return scheduleEntries.filter((scheduleEntry) => {
    return (
      stringToTimestamp(scheduleEntry.start) < dayEnd &&
      stringToTimestamp(scheduleEntry.end) > dayStart
    )
  })
}

function scheduleEntryBorderRadiusStyles(scheduleEntry, day, times) {
  const [dayStart, dayEnd] = dayBoundariesInMinutes(day, times)

  const start = stringToTimestamp(scheduleEntry.start)
  const startsOnThisDay = start >= dayStart && start <= dayEnd

  const end = stringToTimestamp(scheduleEntry.end)
  const endsOnThisDay = end >= dayStart && end <= dayEnd

  return {
    // prettier-ignore
    ...(endsOnThisDay ? {} : { borderBottomRightRadius: '0', borderBottomLeftRadius: '0' }),
    ...(startsOnThisDay ? {} : { borderTopRightRadius: '0', borderTopLeftRadius: '0' }),
  }
}

function scheduleEntryPositionStyles(scheduleEntry, day, times) {
  return {
    top:
      percentage(
        stringToTimestamp(scheduleEntry.start) - stringToTimestamp(day.start),
        times
      ) + '%',
    bottom:
      100 -
      percentage(
        stringToTimestamp(scheduleEntry.end) - stringToTimestamp(day.start),
        times
      ) +
      '%',
  }
}

const columnStyles = {
  flexBasis: 0,
  flexGrow: 1,
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
  position: 'relative',
}
const dayGridStyles = {
  width: '100%',
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
}
const dayGridRowStyles = {
  display: 'flex',
  flexBasis: 0,
}
const scheduleEntryColumnStyles = {
  margin: '0 2pt',
  position: 'absolute',
  top: '0',
  bottom: '0',
  left: '0',
  right: '0',
}

function DayColumn({ times, scheduleEntries, day, styles }) {
  return (
    <View style={{ ...columnStyles, ...styles }}>
      <View style={dayGridStyles}>
        {times.slice(0, times.length - 1).map(([time, weight], index) => (
          <View
            key={time}
            style={{
              ...dayGridRowStyles,
              flexGrow: weight,
              ...(index % 2 === 0 ? { backgroundColor: 'lightgrey' } : {}),
            }}
          />
        ))}
      </View>
      <View style={scheduleEntryColumnStyles}>
        {filterScheduleEntriesByDay(scheduleEntries, day, times).map((scheduleEntry) => {
          return (
            <ScheduleEntry
              key={scheduleEntry.id}
              scheduleEntry={scheduleEntry}
              styles={{
                ...scheduleEntryPositionStyles(scheduleEntry, day, times),
                ...scheduleEntryBorderRadiusStyles(scheduleEntry, day, times),
              }}
            />
          )
        })}
      </View>
    </View>
  )
}

export default DayColumn

// frontend/src/pdf/campPrint/picasso/DayColumn.vue
<template>
  <View class="picasso-day-column">
    <View class="picasso-day-column-grid">
      <View
        v-for="([_, weight], index) in times"
        class="picasso-day-column-grid-row"
        :class="{ 'picasso-day-column-grid-row-grey': index % 2 === 1 }"
        :style="{ flexGrow: weight }"
      ></View>
    </View>
    <View class="picasso-day-column-schedule-entry-container">
      <PicassoScheduleEntry
        v-for="scheduleEntry in relevantScheduleEntries"
        :schedule-entry="scheduleEntry"
        :style="{
          ...positionStyles[scheduleEntry.id],
          ...borderRadiusStyles[scheduleEntry.id],
        }"
        :percentage-height="positionStyles[scheduleEntry.id].percentageHeight"
        :config="config"
      />
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import PicassoScheduleEntry from './PicassoScheduleEntry.vue'
import {
  filterScheduleEntriesByDay,
  dayStart,
  dayEnd,
  positionStyles,
} from '../../../common/helpers/picasso.js'

import keyBy from 'lodash-es/keyBy.js'

export default {
  name: 'DayColumn',
  components: { PicassoScheduleEntry },
  extends: PdfComponent,
  props: {
    times: { type: Array, required: true },
    day: { type: Object, required: true },
    scheduleEntries: { type: Array, default: () => [] },
    config: { type: Object, required: true },
  },
  computed: {
    relevantScheduleEntries() {
      return filterScheduleEntriesByDay(this.scheduleEntries, this.day, this.times)
    },
    positionStyles() {
      return positionStyles(this.relevantScheduleEntries, this.day, this.times)
    },
    borderRadiusStyles() {
      const radius = '2pt'
      return keyBy(
        this.relevantScheduleEntries.map((scheduleEntry) => {
          const start = this.$date.utc(scheduleEntry.start)
          const startsOnThisDay =
            start.isSameOrAfter(dayStart(this.day, this.times)) &&
            start.isSameOrBefore(dayEnd(this.day, this.times))
          const topStyles = startsOnThisDay
            ? { borderTopRightRadius: radius, borderTopLeftRadius: radius }
            : {}

          const end = this.$date.utc(scheduleEntry.end)
          const endsOnThisDay =
            end.isSameOrAfter(dayStart(this.day, this.times)) &&
            end.isSameOrBefore(dayEnd(this.day, this.times))
          const bottomStyles = endsOnThisDay
            ? { borderBottomRightRadius: radius, borderBottomLeftRadius: radius }
            : {}

          return { id: scheduleEntry.id, ...bottomStyles, ...topStyles }
        }),
        'id'
      )
    },
  },
}
</script>
<style lang="react-pdf">
.picasso-day-column {
  flex-basis: 0;
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
}
.picasso-day-column-grid {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
}
.picasso-day-column-grid-row {
  display: flex;
  flex-basis: 0;
}
.picasso-day-column-grid-row-grey {
  background-color: lightgrey;
}
.picasso-day-column-schedule-entry-container {
  margin: 0 2pt;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>
