// frontend/src/components/print/print-react/components/picasso/DayHeader.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import dayjs from '@/common/helpers/dayjs.js'
import picassoStyles from './picassoStyles.js'
import campCollaborationDisplayName from '../../../../../common/helpers/campCollaborationDisplayName.js'

function renderDate(day) {
  return dayjs.utc(day.start).hour(0).minute(0).second(0).format('ddd LL')
}

function dayResponsibles(day, $tc) {
  const responsibles = day.dayResponsibles().items
  if (responsibles.length === 0) return ''
  const label = $tc('entity.day.fields.dayResponsibles')
  const displayNames = responsibles
    .map((responsible) => campCollaborationDisplayName(responsible.campCollaboration()))
    .join(', ')
  return `${label}: ${displayNames}`
}

function DayHeader({ day, showDayResponsibles, $tc, styles }) {
  return (
    <View style={{ ...picassoStyles.dayHeader, ...styles }}>
      <Text style={picassoStyles.dayHeaderText}>{renderDate(day)}</Text>
      {showDayResponsibles ? (
        <View style={picassoStyles.dayResponsibles}>
          <Text>{dayResponsibles(day, $tc)}</Text>
        </View>
      ) : (
        <React.Fragment />
      )}
    </View>
  )
}

export default DayHeader

// frontend/src/pdf/campPrint/picasso/DayHeader.vue
<template>
  <View>
    <Text class="picasso-day-header-text">{{ date }}</Text>
    <View v-if="showDayResponsibles" class="picasso-day-responsibles">
      <Text class="picasso-day-responsibles-text">{{ dayResponsibles }}</Text>
    </View>
  </View>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import {
  dayResponsiblesCommaSeparated,
  filterDayResponsiblesByDay,
} from '../../../common/helpers/dayResponsibles.js'

export default {
  name: 'DayHeader',
  extends: PdfComponent,
  props: {
    day: { type: Object, required: true },
    showDayResponsibles: { type: Boolean, default: false },
  },
  computed: {
    date() {
      return this.$date
        .utc(this.day.start)
        .hour(0)
        .minute(0)
        .second(0)
        .format(this.$tc('global.datetime.dateLong'))
    },
    dayResponsibles() {
      if (filterDayResponsiblesByDay(this.day).length === 0) return ''
      const label = this.$tc('entity.day.fields.dayResponsibles')
      const displayNames = dayResponsiblesCommaSeparated(this.day, this.$tc)
      return `${label}: ${displayNames}`
    },
  },
}
</script>
<style lang="react-pdf">
.picasso-day-header-text {
  font-size: 8pt;
  font-weight: bold;
  margin: 0 auto 2pt;
}
.picasso-day-responsibles {
  font-size: 8pt;
  margin: 3pt auto 0;
  line-height: 1.3;
}
.picasso-day-responsibles-text {
  padding-bottom: 5pt;
}
</style>
