// frontend/src/components/print/print-react/components/picasso/PicassoPage.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Page, Text, View } from '@react-pdf/renderer'
import styles from '../styles.js'
import picassoStyles from './picassoStyles.js'
import TimeColumn from './TimeColumn.jsx'
import DayColumn from './DayColumn.jsx'
import TimeColumnSpacer from './TimeColumnSpacer.jsx'
import DayHeader from './DayHeader.jsx'
import PicassoFooter from './PicassoFooter.jsx'
import YSLogo from './YSLogo.jsx'
import Categories from './Categories.jsx'
import { filterDayResponsiblesByDay } from '../../../../../common/helpers/dayResponsibles.js'

/**
 * Generates an array of time row descriptions, used for labeling the vertical axis of the picasso.
 * Format of each array element: [hour, weight] where weight determines how tall the time row is rendered.
 *
 * @param getUpTime the first time row (the very top of the picasso)
 * @param bedtime the last time row (the very bottom of the picasso)
 * @param timeStep size of the time rows, in hours
 * @returns {*[[hour: number, weight: number]]}
 */
function generateTimes({ getUpTime, bedtime, timeStep }) {
  const times = [[getUpTime - timeStep / 2, 0.5]]
  for (let i = 0; getUpTime + i * timeStep < bedtime; i++) {
    // TODO The weight could also be generated depending on the schedule entries present in the camp:
    //   e.g. give less weight to hours that contain no schedule entries.
    const weight = 1
    times.push([getUpTime + i * timeStep, weight])
  }
  times.push([bedtime, 0.5])
  // this last hour is only needed for defining the length of the day. The weight should be 0.
  times.push([bedtime + timeStep / 2, 0])
  return times
}

function PicassoPage(props) {
  const period = props.period
  const days = props.days
  const orientation = props.content.options.orientation
  const anyDayResponsibles = days.some(
    (day) => filterDayResponsiblesByDay(day).length > 0
  )
  const scheduleEntries = period.scheduleEntries().items
  const times = generateTimes({
    getUpTime: props.getUpTime,
    bedtime: props.bedtime,
    timeStep: props.timeStep,
  })

  return (
    <Page
      size="A4"
      orientation={orientation === 'L' ? 'landscape' : 'portrait'}
      style={styles.page}
      key={period._meta.self}
    >
      <View style={picassoStyles.titleContainer}>
        <Text
          id={`${props.id}-${period.id}`}
          bookmark={{
            title: props.$tc('print.picasso.title', { period: period.description }),
            fit: true,
          }}
          style={{ ...styles.h1, ...picassoStyles.title }}
        >
          {props.$tc('print.picasso.title', { period: period.description })}
        </Text>
        <Text>{period.camp().organizer}</Text>
        {period.camp().printYSLogoOnPicasso ? (
          <YSLogo
            size={picassoStyles.ysLogo.size}
            styles={picassoStyles.ysLogo}
            locale={props.locale}
          />
        ) : (
          <React.Fragment />
        )}
      </View>
      <View style={{ ...picassoStyles.calendarContainer, border: '1pt solid white' }}>
        <TimeColumnSpacer times={times.slice(0, times.length - 1)} />
        {days.map((day) => (
          <DayHeader
            day={day}
            showDayResponsibles={anyDayResponsibles}
            key={day.id}
            styles={{
              borderLeft: day.id === days[0].id ? '1pt solid white' : '',
              borderRight: '1pt solid white',
            }}
            {...props}
          />
        ))}
        <TimeColumnSpacer times={times.slice(0, times.length - 1)} />
      </View>
      <View style={picassoStyles.calendarContainer}>
        <TimeColumn times={times.slice(0, times.length - 1)} align={'right'} />
        {days.map((day) => {
          return (
            <DayColumn
              key={day.id}
              styles={{
                borderLeft: day.id === days[0].id ? '1pt solid grey' : '',
                borderRight: '1pt solid grey',
              }}
              times={times}
              day={day}
              scheduleEntries={scheduleEntries}
            />
          )
        })}
        <TimeColumn times={times.slice(0, times.length - 1)} align={'left'} />
      </View>
      <Categories period={period} />
      <PicassoFooter period={period} {...props} />
    </Page>
  )
}

export default PicassoPage

// frontend/src/pdf/campPrint/picasso/PicassoPage.vue
<template>
  <Page :size="config.options.pageSize || 'A4'" :orientation="orientation" class="page">
    <slot></slot>
    <TocSectionStartMarker :id="`${id}-${period.id}`" />
    <View class="picasso-title-container">
      <YSLogo
        v-if="period.camp().printYSLogoOnPicasso"
        :size="20"
        :locale="config.language"
        class="picasso-ys-logo"
      />
      <Text :id="`${id}-${period.id}`" :bookmark="bookmark" class="picasso-title">
        {{ $tc('print.picasso.title', { period: period.description }) }}
      </Text>
      <Text class="picasso-organizer">{{ period.camp().organizer }}</Text>
    </View>
    <View class="picasso-calendar-header-container">
      <TimeColumnSpacer :times="times.slice(0, times.length - 1)" />
      <DayHeader
        v-for="day in days"
        :day="day"
        :show-day-responsibles="anyDayResponsibles"
        class="picasso-day-header"
        :class="{ 'picasso-day-header-left-border': day.id === days[0].id }"
      />
      <TimeColumnSpacer :times="times.slice(0, times.length - 1)" />
    </View>
    <View class="picasso-calendar-container">
      <TimeColumn :times="times.slice(0, times.length - 1)" align="right" />
      <DayColumn
        v-for="day in days"
        :times="times"
        :day="day"
        :schedule-entries="scheduleEntries"
        :class="{ 'picasso-day-column-left-border': day.id === days[0].id }"
        :config="config"
      />
      <TimeColumn :times="times.slice(0, times.length - 1)" align="left" />
    </View>
    <Categories :period="period" :schedule-entries="scheduleEntries" />
    <PicassoFooter :period="period" :locale="config.locale" />
  </Page>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import YSLogo from '../YSLogo.vue'
import TimeColumnSpacer from './TimeColumnSpacer.vue'
import DayHeader from './DayHeader.vue'
import TimeColumn from './TimeColumn.vue'
import DayColumn from './DayColumn.vue'
import Categories from './Categories.vue'
import PicassoFooter from './PicassoFooter.vue'
import { filterDayResponsiblesByDay } from '@/common/helpers/dayResponsibles.js'
import { times } from '@/common/helpers/picasso.js'
import { filterMatchScheduleEntry } from '@/common/helpers/filterMatchScheduleEntry.js'
import TocSectionStartMarker from '../TocSectionStartMarker.vue'

export default {
  name: 'PicassoPage',
  components: {
    TocSectionStartMarker,
    YSLogo,
    TimeColumnSpacer,
    DayHeader,
    TimeColumn,
    DayColumn,
    Categories,
    PicassoFooter,
  },
  extends: PdfComponent,
  props: {
    config: { type: Object, required: true },
    content: { type: Object, required: true },
    period: { type: Object, required: true },
    days: { type: Object, required: true },
    bedtime: { type: Number, default: 0 },
    getUpTime: { type: Number, default: 24 },
    timeStep: { type: Number, default: 1 },
  },
  computed: {
    bookmark() {
      return {
        title: this.$tc('print.picasso.title', {
          period: this.period.description,
        }),
        fit: true,
      }
    },
    times() {
      return times(this.getUpTime, this.bedtime, this.timeStep)
    },
    orientation() {
      return this.content.options.orientation === 'L' ? 'landscape' : 'portrait'
    },
    anyDayResponsibles() {
      return this.days.some((day) => filterDayResponsiblesByDay(day).length > 0)
    },
    scheduleEntries() {
      return this.period.scheduleEntries().items.filter((scheduleEntry) => {
        return filterMatchScheduleEntry(scheduleEntry, this.content.options.filter)
      })
    },
  },
}
</script>
<style lang="react-pdf">
.picasso-title-container {
  display: flex;
  flex-direction: row;
  margin-top: -4pt;
  margin-bottom: 4pt;
  align-items: center;
  gap: 8pt;
}
.picasso-title {
  flex-grow: 1;
  font-weight: bold;
  font-size: 14pt;
}
.picasso-organizer {
  font-size: 10pt;
}
.picasso-ys-logo {
  align-self: flex-end;
  margin-top: 3pt;
  size: 20pt;
}
.picasso-calendar-header-container {
  border-left: 1pt solid white;
  border-right: 1pt solid white;
  flex-grow: 1;
  display: flex;
  flex-direction: row;
  line-height: 0.8;
}
.picasso-calendar-container {
  border: 1pt solid grey;
  flex-grow: 1;
  display: flex;
  flex-direction: row;
}
.picasso-day-header {
  border-right: 1pt solid white;
  flex-basis: 0;
  flex-grow: 1;
  overflow: hidden;
  padding: 4pt 0 5pt;
  display: flex;
  flex-direction: column;
}
.picasso-day-header-left-border {
  border-left: 1pt solid white;
}
.picasso-time-column {
  flex-grow: 0;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
}
.picasso-time-column-text {
  font-size: 8pt;
}
.picasso-day-column-left-border {
  border-left: 1pt solid grey;
}
</style>
