// pdf/src/campPrint/RichText.vue
<script>
import PdfComponent from '@/PdfComponent.js'
import HTML from 'html-parse-stringify'
import { decode } from 'html-entities'
// eslint-disable-next-line vue/prefer-import-from-vue
import { h } from '@vue/runtime-core'
import Text from '@/renderer/components/Text.vue'
import View from '@/renderer/components/View.vue'

function visit(node, parent = null) {
  const rule = rules.find((rule) => rule.shouldProcessNode(node, parent))
  if (!rule) {
    console.log('unknown HTML node type', node)
    return null
  }

  return rule.processNode(node, parent)
}

function visitChildren(children, parent) {
  return () =>
    children.length
      ? children.map((child) => visit(child, parent))
      : [visit({ type: 'text', content: '&nbsp;' }, parent)]
}

const rules = [
  {
    shouldProcessNode: (node) => node.type === 'text',
    processNode: (node) => h(Text, {}, () => decode(node.content, { scope: 'strict' })),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && node.name === 'p',
    processNode: (node) => h(Text, { class: 'p' }, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && node.name === 'br',
    processNode: (_) => h(Text, {}, () => [visit({ type: 'text', content: '\n' }, null)]),
  },
  {
    shouldProcessNode: (node) =>
      node.type === 'tag' && ['h1', 'h2', 'h3'].includes(node.name),
    processNode: function (node) {
      return h(Text, { class: node.name }, visitChildren(node.children, node))
    },
  },
  {
    shouldProcessNode: (node) =>
      node.type === 'tag' && (node.name === 'strong' || node.name === 'b'),
    processNode: (node) => h(Text, { class: 'bold' }, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && node.name === 'em',
    processNode: (node) =>
      h(Text, { class: 'italic' }, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && node.name === 'u',
    processNode: (node) =>
      h(Text, { class: 'underlined' }, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) =>
      node.type === 'tag' && (node.name === 's' || node.name === 'strike'),
    processNode: (node) =>
      h(Text, { class: 'strikethrough' }, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && ['ul', 'ol'].includes(node.name),
    processNode: (node) => h(View, visitChildren(node.children, node)),
  },
  {
    shouldProcessNode: (node) => node.type === 'tag' && node.name === 'li',
    processNode: (node, parent) => {
      if (parent.name === 'ul') {
        node.children[0].children[0].content = '• ' + node.children[0].children[0].content
      } else if (parent.name === 'ol') {
        const number =
          parent.children
            .filter((child) => child.type === 'tag' && child.name === 'li')
            .indexOf(node) + 1
        node.children[0].children[0].content =
          `${number}. ` + node.children[0].children[0].content
      }
      return h(View, { style: { marginLeft: '4pt' } }, visitChildren(node.children, node))
    },
  },
]

export default {
  name: 'RichText',
  extends: PdfComponent,
  props: {
    richText: { type: String, default: '' },
  },
  computed: {
    parsed() {
      return HTML.parse(this.richText)
    },
  },
  render() {
    return [this.parsed].flat().map((node) => visit(node))
  },
}
</script>
<pdf-style>
.p {
  margin-bottom: 2pt;
}
.bold {
  font-weight: bold;
}
.italic {
  font-style: italic;
}
.underlined {
  text-decoration: underline;
}
.strikethrough {
  text-decoration: line-through;
}
</pdf-style>

// frontend/src/components/print/RichText.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import { Parser } from 'html-to-react'

const { Text, View } = pdf

function addKeys (children) {
  return children.map((child, idx) => ({ ...child, key: idx }))
}

const richTextRules = [
  {
    shouldProcessNode: function (node) {
      return node.type === 'text'
    },
    processNode: function (node, children) {
      return <Text>{node.data}</Text>
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return node.type === 'tag' && node.name === 'p'
    },
    processNode: function (node, children) {
      return children.length ? <Text>{ addKeys(children) }</Text> : <Text> </Text>
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return node.type === 'tag' && (node.name === 'strong' || node.name === 'b')
    },
    processNode: function (node, children) {
      return <Text style={{ fontWeight: 'bold' }}>{ addKeys(children) }</Text>
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return node.type === 'tag' && node.name === 'ul'
    },
    processNode: function (node, children) {
      return children
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return node.type === 'tag' && node.name === 'ol' // TODO implement ordered list enumeration
    },
    processNode: function (node, children) {
      return children
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return node.type === 'tag' && node.name === 'li'
    },
    processNode: function (node, children) {
      return <Text style={{ marginLeft: '4pt' }}>• {children}</Text>
    }
  },
  {
    replaceChildren: true,
    shouldProcessNode: function (node) {
      return true
    },
    processNode: function (node, children) {
      console.log('unknown HTML node type', node, children)
      return <View/>
    }
  }
]

function RichText ({ richText }) {
  if (!richText) return <View/>
  const htmlToReactParser = new Parser()
  return htmlToReactParser.parseWithInstructions(richText, () => true, richTextRules)
}

export default RichText
