// pdf/src/campPrint/scheduleEntry/ScheduleEntry.vue
<template>
  <View :wrap="false" :min-presence-ahead="75">
    <View class="schedule-entry-header-title">
      <View class="h1 schedule-entry-title">
        <Text
          :id="id"
          :bookmark="{ title: bookmarkTitle, fit: true }"
          style="margin: 4pt 0"
        >
          {{ scheduleEntry.number }}
        </Text>
        <CategoryLabel :category="activity.category()" style="margin: 4pt 3pt" />
        <Text style="margin: 4pt 0">{{ activity.title }}</Text>
      </View>
      <View class="schedule-entry-date">
        <View class="schedule-entry-date-text">
          <Text>{{ startAt }}</Text>
        </View>
        <View class="schedule-entry-date-text">
          <Text>- {{ endAt }}</Text>
        </View>
      </View>
    </View>
    <View class="schedule-entry-header">
      <View class="schedule-entry-header-left">
        <Text class="schedule-entry-header-metadata-label">{{
          $tc('entity.activity.fields.location')
        }}</Text>
        <Text class="schedule-entry-header-metadata-label">{{
          $tc('entity.activity.fields.responsible')
        }}</Text>
      </View>
      <View class="schedule-entry-header-right">
        <Text class="schedule-entry-header-metadata-value">{{ activity.location }}</Text>
        <Responsibles class="schedule-entry-header-metadata-value" :activity="activity" />
      </View>
    </View>
  </View>
  <View style="margin-bottom: 20pt">
    <ContentNode :content-node="activity.rootContentNode()" />
  </View>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import CategoryLabel from '../CategoryLabel.vue'
import Responsibles from '../picasso/Responsibles.vue'
import ContentNode from './contentNode/ContentNode.vue'
import { setContentNodeComponent } from './contentNode/ColumnLayout.vue'

setContentNodeComponent(ContentNode)

export default {
  name: 'ScheduleEntry',
  components: { Responsibles, CategoryLabel, ContentNode },
  extends: PdfComponent,
  props: {
    scheduleEntry: { type: Object, required: true },
  },
  computed: {
    activity() {
      return this.scheduleEntry.activity()
    },
    bookmarkTitle() {
      return (
        this.activity.category().short +
        ' ' +
        this.scheduleEntry.number +
        ' ' +
        this.activity.title
      )
    },
    start() {
      return this.$date.utc(this.scheduleEntry.start)
    },
    end() {
      return this.$date.utc(this.scheduleEntry.end)
    },
    startAt() {
      return this.start.format('ddd l LT')
    },
    endAt() {
      return this.start.format('ddd l') === this.end.format('ddd l')
        ? this.end.format('LT')
        : this.end.format('ddd l LT')
    },
  },
}
</script>
<pdf-style>
.schedule-entry-header-title {
  display: flex;
  flex-direction: row;
  border-bottom: 1px solid black;
  padding-bottom: 8pt;
}
.schedule-entry-title {
  flex-grow: 1;
  display: flex;
  flex-direction: row;
}
.schedule-entry-date {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
.schedule-entry-date-text {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
}
.schedule-entry-header {
  display: flex;
  flex-direction: row;
}
.schedule-entry-header-left {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  border-right: 1px solid black;
}
.schedule-entry-header-right {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}
.schedule-entry-header-metadata-label {
  height: 16pt;
  border-bottom: 1px solid black;
  padding: 2pt 4pt 2pt 0;
}
.schedule-entry-header-metadata-value {
  height: 16pt;
  border-bottom: 1px solid black;
  overflow: ellipsis;
  padding: 2pt 0 2pt 4pt;
}
</pdf-style>

// frontend/src/components/print/scheduleEntry/ScheduleEntry.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import styles from '../styles.js'
import Responsibles from '../picasso/Responsibles.jsx'
import dayjs from '../../../../../common/helpers/dayjs.js'
import ContentNode from './contentNode/ContentNode.jsx'

const { View, Text } = pdf

const fontSize = 8

const categoryLabelStyles = {
  borderRadius: '50%',
  padding: '4pt 8pt'
}

function ScheduleEntry (props) {
  const scheduleEntry = props.scheduleEntry
  const activity = scheduleEntry.activity()
  const start = dayjs.utc(scheduleEntry.start)
  const end = dayjs.utc(scheduleEntry.end)
  const startAt = start.format('ddd l LT')
  const endAt = start.format('ddd l') === end.format('ddd l') ? end.format('LT') : end.format('ddd l LT')

  return <React.Fragment>
    <View wrap={false} minPresenceAhead={75}>
      <View style={{ display: 'flex', flexDirection: 'row', borderBottom: '1px solid black', paddingBottom: '8pt' }}>
        <Text id={'scheduleEntry-' + scheduleEntry.id} style={{ ...styles.h1, padding: '4pt 0' }}>{ scheduleEntry.number } </Text>
        <Text style={{ ...styles.h1, ...categoryLabelStyles, backgroundColor: activity.category().color }}>{activity.category().short}</Text>
        <Text style={{ ...styles.h1, padding: '4pt', flexGrow: '1', overflow: 'ellipsis' }}>{activity.title}</Text>
        <View style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'flex-end' }}><Text>{ startAt }</Text></View>
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'flex-end' }}><Text>- { endAt }</Text></View>
        </View>
      </View>
      <View style={{ display: 'flex', flexDirection: 'row' }}>
        <View style={{ display: 'flex', flexDirection: 'column', flexShrink: '0', borderRight: '1px solid black' }}>
          <Text style={{ height: (fontSize + 8) + 'pt', borderBottom: '1px solid black', padding: '2pt 4pt 2pt 0' }}>{ props.$tc('entity.activity.fields.location') }</Text>
          <Text style={{ height: (fontSize + 8) + 'pt', borderBottom: '1px solid black', padding: '2pt 4pt 2pt 0' }}>{ props.$tc('entity.activity.fields.responsible') }</Text>
        </View>
        <View style={{ display: 'flex', flexDirection: 'column', flexGrow: '1' }}>
          <Text style={{ height: (fontSize + 8) + 'pt', borderBottom: '1px solid black', overflow: 'ellipsis', padding: '2pt 0 2pt 4pt' }}>{ activity.location }</Text>
          <Responsibles styles={{ height: (fontSize + 8) + 'pt', borderBottom: '1px solid black', padding: '2pt 0 2pt 4pt' }} activity={activity} />
        </View>
      </View>
    </View>
    <View style={{ marginBottom: '20pt' }}>
      <ContentNode {...props} contentNode={activity.rootContentNode()} />
    </View>
  </React.Fragment>
}

export default ScheduleEntry
