// print/components/generic/CategoryLabel.vue
<template>
  <span class="category-label" :style="style()">{{ category.short }}</span>
</template>

<script>
import { parseHexColor, contrastColor } from '@/../common/helpers/colors.js'

export default {
  props: {
    category: { type: Object, required: true },
  },
  async fetch() {
    await Promise.all([this.category._meta.load])
  },
  methods: {
    style() {
      return {
        backgroundColor: this.category.color,
        color: contrastColor(...parseHexColor(this.category.color)),
      }
    },
  },
}
</script>

<style lang="scss">
.category-label {
  padding: 0.1rem 0.6rem;
  border-radius: 999px;
}
</style>

// frontend/src/components/print/print-react/components/CategoryLabel.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Text } from '@react-pdf/renderer'
import styles from './styles.js'
import { parseHexColor, contrastColor } from '@/common/helpers/colors.js'

function textColor(color) {
  return contrastColor(...parseHexColor(color))
}

function CategoryLabel({ activity, style }) {
  return (
    <Text
      style={{
        ...styles.categoryLabel,
        color: textColor(activity.category().color),
        backgroundColor: activity.category().color,
        ...style,
      }}
    >
      {activity.category().short}
    </Text>
  )
}

export default CategoryLabel
