// pdf/src/campPrint/scheduleEntry/contentNode/ContentNode.vue
<template>
  <component
    :is="contentNodeComponent"
    v-if="contentNodeComponent"
    :content-node="contentNode"
  />
  <Text v-else>{{ contentTypeName }}</Text>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import ColumnLayout from './ColumnLayout.vue'
import LAThematicArea from './LAThematicArea.vue'
import Storyboard from './Storyboard.vue'
import Notes from './Notes.vue'
import SafetyConcept from './SafetyConcept.vue'
import Material from './Material.vue'
import Storycontext from './Storycontext.vue'

export default {
  name: 'ContentNode',
  extends: PdfComponent,
  props: {
    contentNode: { type: Object, required: true },
  },
  computed: {
    contentTypeName() {
      return this.contentNode.contentTypeName
    },
    contentNodeComponent() {
      return {
        ColumnLayout,
        LAThematicArea,
        Storyboard,
        Notes,
        SafetyConcept,
        Material,
        Storycontext,
      }[this.contentTypeName]
    },
  },
}
</script>
<pdf-style>
.content-node {
  margin-bottom: 6pt;
}
</pdf-style>

// frontend/src/components/print/scheduleEntry/contentNode/ContentNode.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import pdf from '@react-pdf/renderer'
import ColumnLayout from './ColumnLayout.jsx'
import LAThematicArea from './LAThematicArea.jsx'
import Storyboard from './Storyboard.jsx'
import Notes from './Notes.jsx'
import SafetyConcept from './SafetyConcept.jsx'
import Material from './Material.jsx'
import Storycontext from './Storycontext.jsx'

const { Text } = pdf

const contentNodeComponents = {
  ColumnLayout,
  LAThematicArea,
  Storyboard,
  Notes,
  SafetyConcept,
  Material,
  Storycontext
}

function ContentNode (props) {
  const contentTypeName = props.contentNode.contentType().name
  if (typeof contentNodeComponents[contentTypeName] !== 'undefined') {
    return React.createElement(contentNodeComponents[contentTypeName], { ...props, ContentNode })
  } else {
    return <Text>{contentTypeName}</Text>
  }
}

export default ContentNode
