// pdf/src/campPrint/tableOfContents/TableOfContents.vue
<template>
  <Page size="A4" class="page">
    <Text :id="id" :bookmark="$tc('print.toc.title')" class="h1">{{
      $tc('print.toc.title')
    }}</Text>
    <template v-for="(entry, index) in config.contents">
      <component
        :is="entryComponents[entry.type]"
        v-if="entry.type in entryComponents"
        :id="`entry-${index}`"
        :key="index"
        :entry="entry"
      ></component>
      <Text v-else :key="`unknown-${index}`">{{ entry.type }}</Text>
    </template>
  </Page>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import Cover from './entry/Cover.vue'
import Toc from './entry/Toc.vue'
import Picasso from './entry/Picasso.vue'
import Program from './entry/Program.vue'
import Activity from './entry/Activity.vue'
import Story from './entry/Story.vue'

export default {
  name: 'Cover',
  extends: PdfComponent,
  props: {
    content: { type: Object, required: true },
    config: { type: Object, required: true },
  },
  computed: {
    entryComponents() {
      return {
        Cover,
        Toc,
        Picasso,
        Program,
        Activity,
        Story,
      }
    },
  },
}
</script>
<pdf-style>
.toc-entry {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
.toc-sub-entry {
  margin-left: 10pt;
}
</pdf-style>

// frontend/src/components/print/print-react/components/tableOfContents/TableOfContents.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Page, Text } from '@react-pdf/renderer'
import styles from '../styles.js'
import Toc from './entry/Toc.jsx'
import Picasso from './entry/Picasso.jsx'
import Program from './entry/Program.jsx'
import Activity from './entry/Activity.jsx'
import Cover from './entry/Cover.jsx'
import Story from './entry/Story.jsx'

const entryComponents = {
  Cover,
  Toc,
  Picasso,
  Program,
  Activity,
  Story,
}

function TableOfContents(props) {
  return (
    <Page size="A4" orientation={'portrait'} style={styles.page}>
      <Text id={props.id} bookmark={props.$tc('print.toc.title')} style={styles.h1}>
        {props.$tc('print.toc.title')}
      </Text>
      {props.config.contents.map((entry, index) => {
        if (typeof entryComponents[entry.type] !== 'undefined') {
          return React.createElement(entryComponents[entry.type], {
            ...props,
            entry,
            id: `entry-${index}`,
            key: index,
          })
        }
        return <Text key={index}>{entry.type}</Text>
      })}
    </Page>
  )
}

export default TableOfContents
