// frontend/src/pdf/campPrint/tableOfContents/entry/Activity.vue
<template>
  <Link v-if="scheduleEntry" class="toc-entry" :href="`#${id}-${scheduleEntry.id}`">
    <Text>
      {{ scheduleEntry.category }}
      {{ scheduleEntry.number }}
      {{ scheduleEntry.title }}
    </Text>
    <TocEntryPageNumber
      v-if="config.options.pageNumbers"
      :id="`${id}-${scheduleEntry.id}`"
    />
  </Link>
</template>
<script>
import PdfComponent from '@/pdf/PdfComponent.js'
import TocEntryPageNumber from '../TocEntryPageNumber.vue'

export default {
  name: 'Activity',
  components: { TocEntryPageNumber },
  extends: PdfComponent,
  props: {
    entry: { type: Object, required: true },
    config: { type: Object, required: true },
  },
  computed: {
    scheduleEntry() {
      if (!this.entry.options.scheduleEntry) return null

      const scheduleEntry = this.api.get(this.entry.options.scheduleEntry)
      const activity = scheduleEntry.activity()
      return {
        ...scheduleEntry,
        category: activity.category().short,
        title: activity.title,
      }
    },
  },
}
</script>
<style lang="react-pdf"></style>

// frontend/src/components/print/print-react/components/tableOfContents/entry/Activity.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Activity(props) {
  if (!props.entry.options.scheduleEntry) {
    return <React.Fragment />
  }

  return [props.entry.options.scheduleEntry].map((scheduleEntryUri) => {
    const scheduleEntry = props.store.get(scheduleEntryUri)
    const activity = scheduleEntry.activity()
    return (
      <Link
        style={tocStyles.entry}
        href={`#${props.id}-${scheduleEntry.id}`}
        key={scheduleEntry.id}
      >
        <Text>
          {activity.category().short + ' ' + scheduleEntry.number + ' ' + activity.title}
        </Text>
      </Link>
    )
  })
}

export default Activity
