// pdf/src/campPrint/tableOfContents/entry/Cover.vue
<template>
  <Link class="toc-entry" :href="`#${id}`">
    <Text>{{ $tc('print.cover.title') }}</Text>
    <TocEntryPageNumber v-if="config.options.pageNumbers" :id="id" />
  </Link>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import TocEntryPageNumber from '../TocEntryPageNumber.vue'

export default {
  name: 'Cover',
  components: { TocEntryPageNumber },
  extends: PdfComponent,
  props: {
    config: { type: Object, required: true },
  },
}
</script>
<style lang="react-pdf"></style>

// frontend/src/components/print/print-react/components/tableOfContents/entry/Cover.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Cover(props) {
  return (
    <Link style={tocStyles.entry} href={`#${props.id}`}>
      <Text>{props.$tc('print.cover.title')}</Text>
    </Link>
  )
}

export default Cover
