// pdf/src/campPrint/picasso/Picasso.vue
<template>
  <PicassoPeriod
    v-for="period in periods"
    :id="id"
    :key="period.id"
    :config="config"
    :content="content"
    :period="period"
  />
</template>
<script>
import PdfComponent from '@/PdfComponent.js'
import PicassoPeriod from './PicassoPeriod.vue'

export default {
  name: 'Picasso',
  components: { PicassoPeriod },
  extends: PdfComponent,
  props: {
    config: { type: Object, required: true },
    content: { type: Object, required: true },
  },
  computed: {
    periods() {
      return (this.content.options?.periods || []).map((periodUri) => {
        return this.api.get(periodUri)
      })
    },
  },
}
</script>
<pdf-style>
</pdf-style>

// frontend/src/components/print/print-react/components/tableOfContents/entry/Picasso.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Picasso(props) {
  return props.entry.options.periods.map((periodUri) => {
    const period = props.store.get(periodUri)
    return (
      <Link style={tocStyles.entry} href={`#${props.id}-${period.id}`} key={period.id}>
        <Text>
          {props.$tc('components.picassoChunk.title', { period: period.description })}
        </Text>
      </Link>
    )
  })
}

export default Picasso
