// pdf/src/campPrint/tableOfContents/entry/Story.vue
<template>
  <Link v-for="period in periods" :key="period.id" :href="`#${id}-${period.id}`">
    <Text>{{ $tc('print.story.title') }}: {{ period.description }}</Text>
  </Link>
</template>
<script>
import PdfComponent from '@/PdfComponent.js'

export default {
  name: 'Story',
  extends: PdfComponent,
  props: {
    entry: { type: Object, required: true },
  },
  computed: {
    periods() {
      return this.entry.options.periods.map((periodUri) => this.api.get(periodUri))
    },
  },
}
</script>
<pdf-style>
</pdf-style>

// frontend/src/components/print/print-react/components/tableOfContents/entry/Story.jsx
// eslint-disable-next-line no-unused-vars
import React from 'react'
import { Link, Text } from '@react-pdf/renderer'
import tocStyles from '../tocStyles.js'

function Story(props) {
  return props.entry.options.periods.map((periodUri) => {
    const period = props.store.get(periodUri)
    return (
      <Link style={tocStyles.entry} href={`#${props.id}-${period.id}`} key={periodUri}>
        <Text>
          {props.$tc('print.story.title')}: {period.description}
        </Text>
      </Link>
    )
  })
}

export default Story
